modLoader="javafml"
loaderVersion="[46,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
   modId="forge"
   mandatory=true
   versionRange="[46,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.${mod_id}]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20,1.20.1]"
   ordering="NONE"
   side="BOTH"
[[dependencies.${mod_id}]]
   modId="dragonsurvival"
   mandatory=true
   versionRange="${dragonsurvival_version_range}"
   ordering="AFTER"
   side="BOTH"
